# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts
WORKDIR /app

# Install dependencies including dev for build
COPY package.json package-lock.json ./
RUN npm ci

# Copy source
COPY . .

# Build
RUN npm run build

# Remove dev dependencies to slim image
RUN npm prune --production

# Use non-root user
RUN addgroup --system app && adduser --system --ingroup app app
USER app

# Entrypoint
ENTRYPOINT ["npx", "powertools-mcp"]
