name: Maintenance
description: Suggest an activity to help address tech debt, governance, and anything internal
title: "Maintenance: TITLE"
labels: ["triage"]
type: "Task"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to help us improve this project.
  - type: textarea
    id: activity
    attributes:
      label: Summary
      description: Please provide an overview in one or two paragraphs
    validations:
      required: true
  - type: textarea
    id: importance
    attributes:
      label: Why is this needed?
      description: Please help us understand the value so we can prioritize it accordingly
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Solution
      description: If available, please share what a good solution would look like
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---

        **Disclaimer**: After creating an issue, please wait until it is triaged and confirmed by a maintainer before implementing it. This will reduce amount of rework and the chance that a pull request gets rejected.
  - type: input
    id: notes
    attributes:
      label: Future readers
      description: Please not edit this field
      value: "Please react with 👍 and your use case to help us understand customer demand."