name: Code Quality

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  run-unit-tests:
    uses: ./.github/workflows/reusable-code-quality.yml
  run-e2e-tests:
    uses: ./.github/workflows/reusable-e2e.yml